# Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/${DB_NAME}
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}

# Hibernate
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# HTTP
quarkus.http.port=8080

#api diario
quarkus.rest-client.querido-diario.url=https://api.queridodiario.ok.org.br

quarkus.rest-client.goias-diario.url=https://api.diariooficial.abc.go.gov.br

quarkus.rest-client.mt-diario.url=https://api.iomat.mt.gov.br

quarkus.rest-client.ms-diario.url=https://www.diariooficial.ms.gov.br




#verify token
mp.jwt.verify.issuer=concurso-monitor



#config brevo
quarkus.mailer.host=${BREVO_SMTP_HOST}
quarkus.mailer.port=${BREVO_SMTP_PORT}
quarkus.mailer.username=${BREVO_SMTP_USER}
quarkus.mailer.password=${BREVO_SMTP_PASSWORD}
quarkus.mailer.from=${MAIL_FROM}
quarkus.mailer.start-tls=REQUIRED
quarkus.mailer.mock=false